// Auto-generated by scripts/generate-tracks.ts
// Do not edit manually - run "npm run generate-tracks" to regenerate

import { Track } from '@ym2149/player';

export const tracks: Track[] = [
  {
    "filename": "Credits.ym",
    "displayName": "Synergy Credits Screen.",
    "artist": "Scavenger / Synergy"
  },
  {
    "filename": "Gritty.ym",
    "displayName": "Gritty",
    "artist": "Excellence in Art"
  },
  {
    "filename": "LethalXcess1.ym",
    "displayName": "Lethal XCess Music 1",
    "artist": "Jochen Hippel (MadMax)"
  },
  {
    "filename": "ND-Toxygene.ym",
    "displayName": "Nostalgic-O-Demo Toxygen Music.",
    "artist": "TAO of ACF (Using Sync-Buzzer !!)"
  },
  {
    "filename": "Prelude.ym",
    "displayName": "prelude",
    "artist": "TAO of ACF"
  },
  {
    "filename": "Scout.ym",
    "displayName": "Scout",
    "artist": "Jochen Hippel (Jeroen Tel)"
  },
  {
    "filename": "Steps.ym",
    "displayName": "steps",
    "artist": "TAO of ACF"
  },
  {
    "filename": "SynthDream5.ym",
    "displayName": "Synth Dream Music Disk (Song 5)",
    "artist": "Laurens Tummers"
  },
  {
    "filename": "Wings2.ym",
    "displayName": "Wings2",
    "artist": "-"
  },
  {
    "filename": "4-Mat - Krunk (2006).pt3",
    "displayName": "4-Mat - Krunk (2006)",
    "artist": "-"
  },
  {
    "filename": "DncDick.pt3",
    "displayName": "Dancing dick",
    "artist": "krb 2k6"
  },
  {
    "filename": "Karboflex.pt3",
    "displayName": "'Karboflex' - Theme of Supaplex",
    "artist": "Karbofos of DrinkLover's 2oo5"
  },
  {
    "filename": "m_entryO.pt3",
    "displayName": "...olia iz lukoil'a... compo mix",
    "artist": "siril.4d.perm.ru. o6.o3.2oo1.bac"
  },
  {
    "filename": "myaykrai.pt3",
    "displayName": "kraimaiay",
    "artist": "n1k-o2673"
  },
  {
    "filename": "NoPower.pt3",
    "displayName": "No power",
    "artist": "karbofos [Drink lover's] 2oo5"
  },
  {
    "filename": "TrafOfD.pt3",
    "displayName": "'s p l e e n' .25-7-2oo2. nocopy",
    "artist": "BY NIK-O FOR RGI/POS-WT"
  },
  {
    "filename": "UckA_!a.pt3",
    "displayName": "'UcKa/!a' Zemfira song 4 CC'0o0",
    "artist": "Nik-O_TL: _converted_  07JuLy2k"
  }
];
