import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parseYmFile, parsePt3File } from '@ym2149/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, '../public');
const outputFile = join(__dirname, '../src/tracks.ts');

interface TrackInfo {
  filename: string;
  displayName: string;
  artist: string;
}

function extractMetadata(filename: string): TrackInfo {
  const filepath = join(publicDir, filename);
  const data = new Uint8Array(readFileSync(filepath));

  let displayName = filename.replace(/\.(ym|pt3)$/i, '');
  let artist = '-';

  try {
    if (filename.toLowerCase().endsWith('.pt3')) {
      const pt3 = parsePt3File(data);
      if (pt3.title?.trim()) displayName = pt3.title.trim();
      if (pt3.author?.trim()) artist = pt3.author.trim();
    } else {
      const ym = parseYmFile(data);
      if (ym.metadata.songName?.trim()) displayName = ym.metadata.songName.trim();
      if (ym.metadata.author?.trim()) artist = ym.metadata.author.trim();
    }
  } catch (err) {
    console.warn(`Warning: Could not parse ${filename}:`, (err as Error).message);
  }

  return { filename, displayName, artist };
}

function generateTracks(): void {
  const files = readdirSync(publicDir)
    .filter(f => /\.(ym|pt3)$/i.test(f))
    .sort((a, b) => {
      // Sort YM files first, then PT3
      const aIsYm = a.toLowerCase().endsWith('.ym');
      const bIsYm = b.toLowerCase().endsWith('.ym');
      if (aIsYm !== bIsYm) return aIsYm ? -1 : 1;
      return a.localeCompare(b);
    });

  const tracks = files.map(extractMetadata);

  const content = `// Auto-generated by scripts/generate-tracks.ts
// Do not edit manually - run "npm run generate-tracks" to regenerate

import { Track } from '@ym2149/player';

export const tracks: Track[] = ${JSON.stringify(tracks, null, 2)};
`;

  writeFileSync(outputFile, content);
  console.log(`Generated ${tracks.length} tracks in src/tracks.ts`);
}

generateTracks();
